image: docker:latest

cache:
  paths:
    - .m2/repository
    
stages:
- build
- release
- deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  RELEASE_IMAGE: imagens.labci.br/app:$CI_COMMIT_TAG
  TZ: America/Sao_Paulo

Compilando:
  image: maven
  stage: build
  script:
    - "mvn clean install"
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - target/*.war
    expire_in: 1 week    
  only:
    - tags

Imagem_Docker:
  stage: release
  script:
    - docker build --pull -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE
  only:
    - tags

Deploy_App:
  stage: deploy
  before_script:
        - apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "${SSH_DOCKER_LAB}" | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
  script:
    #- ssh -o StrictHostKeyChecking=no ubuntu@docker.labci.br "docker stack deploy -c ~/lab-gitlabci/sample-web-application/docker-compose.yml lab"  
    - ssh -o StrictHostKeyChecking=no ubuntu@docker.labci.br "docker service update --image imagens.labci.br/app:$CI_COMMIT_TAG lab_app"
  only:
    - tags